# reports/markdown_reporter.py
import os
import json
from datetime import datetime, timezone
from pathlib import Path


def generate_markdown(rca: dict, raw_data: dict, output_dir: str = "./output") -> str:
    """Generate a Markdown RCA report and return the file path."""

    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    report_dir = Path(output_dir) / ts
    report_dir.mkdir(parents=True, exist_ok=True)
    filepath = report_dir / "rca_report.md"

    sev = rca.get("overall_severity", "UNKNOWN")
    sev_emoji = {
        "CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢", "NONE": "✅"
    }.get(sev, "⚪")

    rc = rca.get("root_cause", {})
    scope = rca.get("affected_scope", {})
    steps = rca.get("recommended_steps", [])
    factors = rca.get("contributing_factors", [])
    gaps = rca.get("data_gaps", [])

    lines = [
        f"# 📡 Network RCA Report",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Generated** | {rca.get('rca_timestamp', ts)} |",
        f"| **Severity** | {sev_emoji} {sev} |",
        f"| **Issue Detected** | {'Yes' if rca.get('issue_detected') else 'No'} |",
        f"| **Root Cause Domain** | {rc.get('domain', 'N/A')} |",
        f"| **Confidence** | {rc.get('confidence', 'N/A')} |",
        f"",
        f"---",
        f"",
        f"## 📋 Executive Summary",
        f"",
        rca.get("executive_summary", "_No summary available._"),
        f"",
        f"---",
        f"",
        f"## 🔍 Root Cause Analysis",
        f"",
        f"**Domain:** {rc.get('domain')}",
        f"",
        f"**Description:**",
        f"> {rc.get('description', 'N/A')}",
        f"",
        f"**Supporting Evidence:**",
    ]
    for ev in rc.get("supporting_evidence", []):
        lines.append(f"- {ev}")

    lines += [
        f"",
        f"---",
        f"",
        f"## 👥 Affected Scope",
        f"",
        f"| Item | Value |",
        f"|------|-------|",
        f"| Estimated Users Impacted | {scope.get('estimated_users_impacted', 'Unknown')} |",
        f"| Affected SSIDs | {', '.join(scope.get('affected_ssids', ['N/A'])) or 'N/A'} |",
        f"| Affected APs | {', '.join(scope.get('affected_aps', ['N/A'])) or 'N/A'} |",
        f"| Affected Sites | {', '.join(scope.get('affected_sites', ['N/A'])) or 'N/A'} |",
        f"",
    ]

    if factors:
        lines += [f"---", f"", f"## ⚠️ Contributing Factors", f""]
        for i, f_ in enumerate(factors, 1):
            lines.append(f"### {i}. {f_.get('domain')} — {f_.get('severity')}")
            lines.append(f"> {f_.get('description')}")
            lines.append("")

    lines += [f"---", f"", f"## 🛠️ Recommended Remediation Steps", f""]
    for step in steps:
        lines += [
            f"### Step {step['priority']}: {step['action']}",
            f"- **System:** {step.get('system')}",
            f"- **Estimated Time:** {step.get('estimated_time', 'N/A')}",
            f"",
            f"{step.get('detail', '')}",
            f"",
        ]

    if gaps:
        lines += [f"---", f"", f"## ❓ Data Gaps / Limitations", f""]
        for g in gaps:
            lines.append(f"- {g}")

    lines += [
        f"",
        f"---",
        f"",
        f"## 🔁 Next Check Recommendation",
        f"",
        rca.get("next_check_recommendation", "_No recommendation provided._"),
        f"",
        f"---",
        f"",
        f"## 📦 Raw Telemetry Snapshot",
        f"",
        f"```json",
        json.dumps(raw_data, indent=2, default=str)[:5000],  # cap at 5k chars
        f"```",
        f"",
        f"---",
        f"*Report generated by Aruba RCA Automation · Claude claude-sonnet-4*",
    ]

    filepath.write_text("\n".join(lines), encoding="utf-8")
    return str(filepath)
